apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: dockersamples/examplevotingapp_vote
        volumeMounts:
        - name: stylesheet-volume
          mountPath: "/usr/local/app/static/stylesheets/"
          readOnly: true
        name: vote
        ports:
        - containerPort: 80
          name: vote
      volumes:
      - name: stylesheet-volume
        configMap:
          name: vote-stylesheet